# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
evm_version = "osaka"
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 100_000

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.default.optimizer_details.yul_details]
stackAllocation = true

[fuzz]
runs = 4096

[invariant]
runs = 256

[fmt]
line_length = 120
tab_width = 4
sort_imports = true
wrap_comments = true
bracket_spacing = true
override_spacing = true
contract_new_lines = false
single_line_statement_blocks = "multi"
number_underscore = "thousands"
hex_underscore = "bytes"
